### ISSUE TITLE
Add More Detail On How To Build

### ISSUE THREAD

**Issue by opticyclic** [weibel/colorize-gimp#1]
Not everyone is familiar with building C from source.
You should update the readme on how to do it.

On Linux you need to install the gtk libraries first:
sudo aptitude install libgtk2.0-dev

Note that apt-get wont work as well as it wont resolve the dependencies issues properly.

Also libsuitesparse-dev is required for compiling
sudo aptitude install libsuitesparse-dev

You also need the gimp development package
sudo aptitude install libgimp2.0-dev

Windows users will probably need something like CodeBlocks with the MingGW compiler
http://www.codeblocks.org/downloads/binaries

Then get the GTK dependencies from somewhere.

This translated page has a bit of help
http://translate.google.com/translate?hl=en&sl=de&u=http://www.pronix.de/pronix-1212.html&prev=/search%3Fq%3Dbuild%2Ba%2BGIMP%2Bplug-in%2Bon%2Bwindows%2Bcodeblocks%26hl%3Den%26tbo%3Dd%26biw%3D1278%26bih%3D518&sa=X&ei=9WWhUKWtLOrQyAG8jIGIBQ&ved=0CDsQ7gEwAQ

The Makefile wont work on Windows either as it has unix paths in it.

**Comment by weibel** [comment]
I don't have time for testing on a variety of systems, but I'll add your input. Version 4.0.0 of SuiteSparse seems to cause problems. At least from MacPorts on OSX Mountain Lion.
