### ISSUE TITLE
about -lf77blas in MAKEFILE

### ISSUE THREAD

**Issue by reverland** [weibel/colorize-gimp#3]
Hi, I just find I can't compile colorize-gimp on my machine for it cannot locate `f77blas`

```
/usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lf77blas
collect2: ld returned 1 exit status
make: *** [colorize] Error 1
```

So after search the Internet, I modified the 'lf77blas' in makefile to 'lblas' and It works!  Fantastic plug-in!

Maybe you can detect the library in the makefile? I'm not familiar with makefile, just to address the problem here to who have the same problem

**Comment by weibel** [comment]
Thanks for the info. I have added your comment to the Readme for now.

**Comment by reverland** [comment]
Thanks for so quickly reply!  @weibel 
BTW
I don't know why, I may have nothing about suitesparse installed, but colorize-gimp works perfectly……
