### ISSUE TITLE
Solving the Optimization Problem

### ISSUE THREAD

**Issue by RoyiAvital** [weibel/colorize-gimp#4]
Hello,
How did you solve the optimization problem?
Which solver?
Are there size limitations?

Thank You.

**Comment by zinx** [comment]
You can read http://www.cs.huji.ac.il/~yweiss/Colorization/colorization-siggraph04.pdf for the algorithm. It states the problem in the form Ax = b, where A is a sparse asymmetric diagonal matrix and b is the input image.

In colorize-gimp, this sparse matrix problem is solved with libsuitesparse's sparse LU decomposition in UMFPACK (umfpack_di_*), but any sparse matrix solver would work; the size limitations are the memory limits of your computer.

**Comment by RoyiAvital** [comment]
Can you describe the speed and size limitations for an average computer (Core i5, 4GB RAM)?
